services:
  ldap:
    image: ${DOCKER_USER}:ldap-v2-${HPCTS_VERSION}
    hostname: ldap
    container_name: ldap
    environment:
      - CONTAINER_LOG_LEVEL=debug
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - LDAP_TLS_VERIFY_CLIENT=never
    networks:
      - compute

  mysql:
    image: mariadb:${MARIADB_VERSION}
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - compute
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - var_lib_mysql:/var/lib/mysql
    expose:
      - "3306"

  base:
    image: ${DOCKER_USER}:base-v2-${HPCTS_VERSION}
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
    depends_on:
      - ldap
    command: |
      bash -c '
        if [ ! -f /etc/munge/munge.key ]; then
          /usr/sbin/create-munge-key
          chown munge:munge /etc/munge/munge.key
          chmod 400 /etc/munge/munge.key
        fi
        exit 0
      '

  slurmdbd:
    image: ${DOCKER_USER}:slurm-v2-${HPCTS_VERSION}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurmdbd_state:/var/lib/slurm
    expose:
      - "22"
      - "6819"
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 2 bash -c '</dev/tcp/localhost/6819' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s
    depends_on:
      - base
      - ldap
      - mysql

  slurmctld:
    image: ${DOCKER_USER}:slurm-v2-${HPCTS_VERSION}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    restart: unless-stopped
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
      - slurmctld_state:/var/lib/slurm
    expose:
      - "22"
      - "6817"
    depends_on:
      slurmdbd:
        condition: service_healthy
      ldap:
        condition: service_started

  cpn01:
    init: true
    image: ${DOCKER_USER}:slurm-v2-${HPCTS_VERSION}
    command: ["slurmd"]
    hostname: cpn01
    container_name: cpn01
    networks:
      - compute
    cap_add:
      - SYS_ADMIN
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
      - cpn01_slurmd_state:/var/lib/slurm
    expose:
      - "22"
      - "6818"
    depends_on:
      - ldap
      - slurmctld

  cpn02:
    init: true
    image: ${DOCKER_USER}:slurm-v2-${HPCTS_VERSION}
    command: ["slurmd"]
    hostname: cpn02
    container_name: cpn02
    networks:
      - compute
    cap_add:
      - SYS_ADMIN
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
      - cpn02_slurmd_state:/var/lib/slurm
    expose:
      - "22"
      - "6818"
    depends_on:
      - ldap
      - slurmctld

  frontend:
    image: ${DOCKER_USER}:slurm-v2-${HPCTS_VERSION}
    command: ["frontend"]
    hostname: frontend
    container_name: frontend
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    ports:
      - "127.0.0.1:6222:22"
    depends_on:
      - ldap
      - slurmctld

  ondemand:
    image: ${DOCKER_USER}:ondemand-v2-${HPCTS_VERSION}
    command: ["serve"]
    hostname: ondemand
    container_name: ondemand
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    expose:
      - "22"
    ports:
      - "127.0.0.1:3443:3443"
      - "127.0.0.1:5554:5554"
    depends_on:
      - ldap
      - frontend

volumes:
  etc_munge:
  etc_slurm:
  home:
  var_lib_mysql:
  cpn01_slurmd_state:
  cpn02_slurmd_state:
  slurmctld_state:
  slurmdbd_state:

networks:
  compute:
